# Generated by Django 5.1.6 on 2025-02-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_dish_remove_order_items_orderdish_order_dishes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="amount",
        ),
    ]
